# Cấu hình xây dựng
[build]
  base = "."
  publish = "dist/public"
  command = "npm run build"

# Cấu hình functions
[functions]
  directory = "dist/functions"

# Chuyển hướng API đến backend
[[redirects]]
  from = "/api/*"
  to = "https://vocab-learning-api2.onrender.com/api/:splat"
  status = 200
  force = true
  
  # Cấu hình thêm cho API redirects
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "special-key-for-render"

# Headers cho API redirect
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Cache-Control = "no-cache"
    X-Forwarded-Host = "benevolent-sopapilla-c9c9e9.netlify.app"

# Chuyển hướng mặc định cho SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200