[build]
  base = "."
  publish = "dist/public"
  command = "npm run build"

[functions]
  directory = "dist/functions"

[[redirects]]
  from = "/api/*"
  to = "https://vocab-learning-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*", 
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH",
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, X-Requested-With",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200