services:
  - type: web
    name: vocab-learning-api
    env: node
    buildCommand: npm install && cp -r node_modules dist/ && node scripts/server-only.cjs
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Sẽ cấu hình thủ công trong Render dashboard
      - key: ALLOWED_ORIGINS
        value: "https://vocab-learning.netlify.app"