services:
  - type: web
    name: vocab-learning-api2
    env: node
    buildCommand: npm install && node scripts/apply-migrations.js && node scripts/server-only.cjs && cp -r node_modules dist/
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_67sDSLEHNOCm@ep-floral-cake-a1usgp6h-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: ALLOWED_ORIGINS
        value: "https://benevolent-sopapilla-c9c9e9.netlify.app"