services:
  - type: web
    name: vocab-learning-api2
    env: node
    buildCommand: npm install && node scripts/apply-migrations.js && node scripts/server-only.cjs && cp -r node_modules dist/
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Sẽ cấu hình thủ công trong Render dashboard
      - key: ALLOWED_ORIGINS
        value: "https://benevolent-sopapilla-c9c9e9.netlify.app"